language: ruby

rvm:
- ruby-head
- 2.4.3
- 2.3.6
- 2.2.9
- 2.1.10

before_install:
  - gem update --system
install:
  - bundle install --without development
addons:
  apt_packages:
    libmagic-dev
script:
  - bundle exec parallel_rspec spec
